### ISSUE TITLE
core-config-importer container fails to run in docker-compose

### ISSUE THREAD

**Issue by mrjones-plip** [openhie/instant#83]
Steps to reproduce per  [Docker Compose instructions](https://github.com/openhie/instant/tree/master/core/docker) :
1. on an ubuntu 20 machine, install docker and docker compose and then clone this repo
1. cd into `instant/core/docker` in the newly cloned repo
1. run `docker volume create --name=instant` to create the needed volume
1. run `./compose.sh init` 

**Expected** all containers start and you can log into OpenHIM console with `root@openhim.org` and `instant101`
**Actual** all containers start, you can NOT login, `core-config-importer` endless restarts with the error found via `docker logs core-config-importer`:
```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module '/instant/core/docker/importer/volume/openhimConfig.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

You can see it restarting endlessly here:

```
root@open-hei-test:~/instant/core/docker# docker ps|egrep 'STATUS|import'
CONTAINER ID   IMAGE                               COMMAND                  CREATED          STATUS                        PORTS      NAMES
c20de160901e   jembi/instantohie-config-importer   "docker-entrypoint.s…"   16 minutes ago   Restarting (1) 1 second ago              core-config-importer
```

**Workarounds** 
I traced the code and saw that this container was just posting the `openhim-import.json` file to the API to initialize it.  Instead of troubleshooting the missing node dependency, I realized this could be done in a bash one-liner. Couple this with a fancy times `docker inspect` and you're good to go!

```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' openhim-core|xargs -I % sh -c 'curl -k -X POST -H "Content-Type: application/json"  -d @./importer/volume/openhim-import.json -k --user root\@openhim.org:openhim-password https://%:8080/metadata'
```

To keep my project moving, I've just incorporated a slightly more hard coded one liner into a [modified `compose.sh` script](https://github.com/medic/chis-interoperability/blob/master/docker/compose.sh#L19). I would be happy to submit further PRs if there's interest in any of this code!

**Comment by MattyJ007** [comment]
Thanks for picking this up @mrjones-plip 

The README here contained some legacy startup instructions - the Instant startup method has moved on a lot from then. I've added a [PR](https://github.com/openhie/instant/pull/104) with the updated documentation change of how to avoid the files not being found.

The issue here was caused by the instant volume not be populated with data. The volume is populated in the regular startup script `deploy.sh` or the data is pre-existing when using the Instant OpenHIE image.
The new instructions I've added just copy the instant repo into a volume to ensure paths resolve properly - i.e. simulating our docker inside docker startup.
